language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t kokopokomoko/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kokopokomoko/docker-react npm run test

